Input
SergeyGhazaryan/reactInput pull request #1
Opened 2021-03-04 18:23 UTC by SergeyGhazaryan

2021-03-11 15:57 UTC, Karen-Avdalyan requested changes

2021-03-11 15:57 UTC, Karen-Avdalyan commented on src/App.js
> +  const [age, setAge] = useState('');
age is not string

2021-03-11 15:57 UTC, Karen-Avdalyan commented on src/App.js
> +  const [newLastName, setNewLastName] = useState('');
this is not acceptable way to save data

2021-03-12 13:32 UTC, Karen-Avdalyan requested changes

2021-03-12 13:32 UTC, Karen-Avdalyan commented on package.json
> +    "@types/react": "^17.0.2"
Are you using here types? I don't think so.

2021-03-12 13:32 UTC, Karen-Avdalyan commented on src/App.js
> +    // here setVisible(false);
delete the comment

2021-03-12 13:32 UTC, Karen-Avdalyan commented on src/App.js
> +        type='text'
you can put default value to this prop, to not write it every time

2021-03-12 13:32 UTC, Karen-Avdalyan commented on src/App.js
> +        functionality={setFirstName}
change the prop name

2021-03-12 13:32 UTC, Karen-Avdalyan commented on src/Style/styles.css
> +input[type=text], [type=number] {
you can to not write here types

2021-03-12 13:32 UTC, Karen-Avdalyan commented on src/Style/styles.css
> +div {
I don't think that this is a good idea to give every div the same style. Use class instead.

2021-03-12 13:58 UTC, SergeyGhazaryan commented on src/App.js
> +        type='text'
I have number type also

2021-03-12 14:29 UTC, Karen-Avdalyan approved these changes

2021-03-12 16:26 UTC, merged